### ISSUE TITLE
Report: conversations_full

### ISSUE THREAD

**Issue by timotoots** [timotoots/iphonebackuptools#4]
Should include in json mode:
* content
* date_read
* date_delivered
* is_delivered
* is_finished
* is_from_me
* is_read
* is_sent
* link to attached file

**Comment by aguerere** [comment]
Hi @timotoots . I wanted to ask about the conversations_full report enhancements you need. Most of the fields you want me to include are already available:
date_read
date_delivered
is_delivered
is_finished
is_from_me
is_read
is_sent

Please check the attached image 
![screenshot at mar 05 22-45-13](https://user-images.githubusercontent.com/14084214/37011534-07c8d5ba-20c7-11e8-8fbe-deb6ebb0be62.png)

I realize the dates are not in a friendly format, those are integer Mac timestamps. To make these dates human-friendly we need to work a few minutes to spread the SQL statement to manipulate the date (this is a pattern used in other reports). But there are over 30 fields in a message , the query must specify each one instead of just doing "message.*" 

Also, about the **content** field, does this refer to the "message" field visible in the screenshot above?

The only missing field is the **link to attached file** , that one we can include.

**Comment by timotoots** [comment]
It's true for the raw export, but not for json. If you run the same thing with "-f json" then you see only:

  {
    "ID": 389,
    "Date": "??",
    "Service": "iMessage",
    "Chat Name": "+372XXXXXXX",
    "Display Name": "______ ______ <XXXXXXX>"
  },

**Comment by aguerere** [comment]
I realize what you mean. I will add the fields for the formatter so it works with "-f json".

**Comment by aguerere** [comment]
PR created here https://github.com/richinfante/iphonebackuptools/pull/26

**Comment by aguerere** [comment]
Merged
